### ISSUE TITLE
Would you be interested in contributing this back to the master branch?

### ISSUE THREAD

**Issue by neubig** [chantera/dynet-rs#1]
We're always happy to have bindings contributed! If so, send a PR and we'll review it.

**Comment by chantera** [comment]
Thank you for your comment. I'm interested in contributing.
With the current C API, however, we cannot handle C++ exceptions and a Rust program crashes when an exception occurs.
So I am planning to implement `safe` API functions which use try-catch block and set API results through a `status` struct.
I have already implemented this in [primitiv-c API](https://github.com/primitiv/primitiv-c/blob/5fe5d6c49eb1e75e6eaf1c10d95c46aa70b42a70/primitiv_c/functions.cc).
After implementing these safe APIs, I will send PR.

**Comment by neubig** [comment]
Great, thanks a lot!

**Comment by chantera** [comment]
It would be great if DyNet provides C API officially so that developers can create bindings. It will take a long time for me to develop C API since I need to inspect DyNet core carefully and have to decide what functions should be exposed and how exceptions and references should be treated. Aside from C API, I am still willing to develop the binding and want to do it after I finish other projects.

**Comment by neubig** [comment]
Thanks, this is certainly something that might be nice to have, but it's a non-trivial amount of work. We'll consider it.
